In [1]:
import pandas as pd 
import csv
import os

In [30]:
file = "hmeq.csv"
read = pd.read_csv(file)
read_sort = read.sort_values(by = "VALUE",ascending = True)
file_rename = read_sort.rename(columns = {"BAD":"1=Default  0=Paid","LOAN":"Loan Amount","MORTDUE":"Mortgage Due",
                                          "VALUE":"Home Value","REASON":"Reason of Default",
                                          "JOB":"Job","YOJ":"Years at Job",
                                          "DEROG":"Number of major derogatory reports",
                                          "DELINQ":"Number of delinquent credit lines",
                                          "CLAGE":"Age of oldest credit line in months",
                                           "NINQ":"Number of recent credit inquiries",
                                           "CLNO":"Number of credit lines",
                                           "DEBTINC":"Debt-to-income ratio"})

file_rename

,1=Default 0=Paid,Loan Amount,Mortgage Due,Home Value,Reason of Default,Job,Years at Job,Number of major derogatory reports,Number of delinquent credit lines,Age of oldest credit line in months,Number of recent credit inquiries,Number of credit lines,Debt-to-income ratio
3538,0,18600,57300.0,8000.0,DebtCon,Other,6.0,NaN,NaN,68.000000,1.0,17.0,NaN
40,1,3000,NaN,8800.0,HomeImp,Other,2.0,0.0,1.0,77.766667,0.0,3.0,NaN
156,1,5000,NaN,9100.0,HomeImp,Other,1.0,0.0,0.0,54.733333,2.0,8.0,NaN
213,1,5200,NaN,9500.0,DebtCon,Other,1.0,0.0,1.0,81.100000,1.0,2.0,NaN
940,1,9100,NaN,11550.0,HomeImp,Other,NaN,0.0,0.0,51.933333,1.0,3.0,NaN
616,1,7800,NaN,11702.0,HomeImp,Other,0.0,0.0,0.0,44.629592,2.0,7.0,21.271785
3683,0,19400,63508.0,12414.0,DebtCon,Other,5.0,NaN,NaN,64.407605,1.0,16.0,40.570169
4225,1,22000,82000.0,12500.0,DebtCon,ProfExe,3.0,0.0,0.0,117.766667,6.0,23.0,NaN
3757,0,20000,59936.0,12737.0,DebtCon,Other,5.0,NaN,NaN,63.395400,0.0,17.0,40.446579
254,1,5500,NaN,12972.0,HomeImp,Other,1.0,0.0,1.0,82.294266,0.0,2.0,36.986744
248,1,5500,NaN,13770.0,HomeImp,Mgr,5.0,0.0,1.0,167.366667,1.0,8.0,NaN
3707,0,19500,58638.0,13930.0,DebtCon,Other,4.0,NaN,NaN,69.005027,0.0,16.0,42.500025
3655,0,19200,65206.0,13933.0,DebtCon,Other,7.0,NaN,NaN,57.591831,0.0,16.0,42.502435
45,1,3000,NaN,14100.0,HomeImp,Other,1.0,0.0,0.0,104.200000,0.0,19.0,NaN
44,1,3000,NaN,14500.0,HomeImp,Other,3.0,0.0,0.0,9.300000,14.0,2.0,NaN
4155,0,21700,60792.0,14580.0,DebtCon,Other,5.0,NaN,NaN,62.856357,1.0,17.0,40.315819
3739,0,19800,63701.0,14609.0,DebtCon,Other,4.0,NaN,NaN,62.359738,1.0,17.0,41.874198
90,1,4000,7000.0,16020.0,HomeImp,Other,18.0,0.0,1.0,85.800000,2.0,23.0,NaN
1429,1,10900,NaN,16365.0,HomeImp,Other,NaN,0.0,0.0,59.548703,1.0,2.0,24.195904
2,1,1500,13500.0,16700.0,HomeImp,Other,4.0,0.0,0.0,149.466667,1.0,10.0,NaN
24,1,2400,NaN,17180.0,HomeImp,Other,NaN,0.0,0.0,14.566667,3.0,4.0,NaN
88,1,4000,5700.0,18000.0,DebtCon,Other,NaN,0.0,0.0,12.200000,0.0,17.0,NaN
869,1,8800,2800.0,18361.0,HomeImp,Other,2.0,3.0,1.0,107.766667,4.0,3.0,NaN
1320,1,10500,NaN,18600.0,HomeImp,Other,24.0,NaN,NaN,NaN,NaN,NaN,NaN
2546,1,15000,18500.0,19000.0,DebtCon,Other,2.0,0.0,1.0,20.166667,0.0,2.0,NaN
99,1,4100,NaN,19132.0,HomeImp,Other,0.0,0.0,0.0,100.774652,0.0,19.0,33.840920
27,1,2500,15000.0,20200.0,HomeImp,NaN,18.0,0.0,0.0,136.066667,1.0,19.0,NaN
39,1,3000,7000.0,20300.0,HomeImp,Other,3.0,0.0,0.0,50.800000,5.0,9.0,NaN
62,1,3500,19400.0,20494.0,HomeImp,Other,5.0,0.0,0.0,95.933333,0.0,9.0,NaN
437,1,6700,NaN,20631.0,HomeImp,Mgr,4.0,0.0,0.0,174.721834,1.0,8.0,62.246451
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4754,1,25000,110048.0,NaN,DebtCon,Other,1.0,0.0,1.0,126.400000,2.0,24.0,NaN
4755,1,25000,110676.0,NaN,DebtCon,Sales,8.0,2.0,0.0,119.366667,0.0,6.0,NaN
4768,1,25000,86000.0,NaN,DebtCon,Other,14.0,1.0,0.0,144.033333,2.0,40.0,NaN
4771,1,25000,68000.0,NaN,DebtCon,Other,8.0,NaN,1.0,134.766667,3.0,33.0,NaN
4837,1,25400,136322.0,NaN,DebtCon,ProfExe,2.0,0.0,5.0,303.737935,1.0,27.0,16.644674
4914,1,25900,NaN,NaN,DebtCon,Other,20.0,0.0,2.0,190.996565,0.0,22.0,31.162389
4934,1,26000,79714.0,NaN,DebtCon,ProfExe,1.0,0.0,4.0,125.766667,0.0,23.0,NaN
4951,1,26100,73525.0,NaN,DebtCon,Office,3.0,1.0,NaN,106.652298,0.0,6.0,22.508173
5007,1,26500,82859.0,NaN,HomeImp,Office,0.4,2.0,0.0,177.500000,0.0,22.0,NaN
5161,1,27700,83300.0,NaN,HomeImp,Mgr,20.0,1.0,4.0,247.933333,1.0,19.0,NaN
5206,1,28100,75768.0,NaN,DebtCon,Other,9.0,NaN,0.0,133.121867,3.0,33.0,46.751800
5291,1,29000,79000.0,NaN,HomeImp,ProfExe,8.0,0.0,1.0,189.700000,1.0,33.0,NaN
5293,1,29000,101824.0,NaN,DebtCon,Mgr,4.0,2.0,4.0,186.700000,0.0,14.0,NaN
5317,1,29900,22000.0,NaN,DebtCon,Other,2.0,2.0,0.0,81.133333,11.0,10.0,NaN
5336,1,30100,92249.0,NaN,HomeImp,Office,2.0,1.0,0.0,180.680154,0.0,21.0,31.089120
5381,1,30900,106717.0,NaN,DebtCon,Mgr,4.0,2.0,4.0,172.432355,0.0,13.0,47.795906
5405,1,31500,16800.0,NaN,DebtCon,NaN,12.0,1.0,2.0,110.633333,4.0,20.0,NaN
5406,1,31500,15391.0,NaN,HomeImp,NaN,2.6,6.0,1.0,57.833333,0.0,8.0,NaN
5613,1,38000,24447.0,NaN,DebtCon,Office,3.0,0.0,4.0,134.900000,2.0,25.0,NaN
5632,1,38800,31976.0,NaN,DebtCon,Office,2.0,0.0,3.0,134.543886,1.0,24.0,NaN
5661,1,40000,53543.0,NaN,DebtCon,Other,3.5,1.0,8.0,159.300000,2.0,39.0,NaN
5662,1,40000,4742.0,NaN,DebtCon,Mgr,5.0,7.0,1.0,304.366667,6.0,21.0,NaN
5713,1,42000,140000.0,NaN,DebtCon,ProfExe,25.0,2.0,1.0,311.433333,1.0,15.0,NaN
5803,1,49500,247500.0,NaN,NaN,Other,0.0,0.0,4.0,160.333333,2.0,25.0,NaN
5816,1,50000,38000.0,NaN,DebtCon,ProfExe,26.0,7.0,6.0,150.200000,0.0,25.0,NaN
5817,1,50000,26976.0,NaN,DebtCon,Mgr,8.3,1.0,0.0,111.600000,1.0,6.0,NaN
5818,1,50000,106000.0,NaN,DebtCon,Mgr,0.8,0.0,2.0,252.633333,3.0,32.0,NaN
5822,1,50000,30338.0,NaN,DebtCon,Mgr,8.0,0.0,0.0,91.431005,0.0,5.0,35.084001
5826,1,50100,256431.0,NaN,NaN,Other,0.0,0.0,4.0,142.343205,2.0,25.0,3.342570
5828,1,50200,34668.0,NaN,DebtCon,Mgr,7.0,1.0,0.0,117.682548,1.0,5.0,36.724486

In [ ]:
# Create the bins in which Data will be held 
bins = [0, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 80000, 90000, 100000, 200000, 300000, 400000, 500000, 1000000]
# Create the names for the four bins
group_names = ["<10,000", "10,000-19,999", "20,000-29,999", "30,000-39,999", "40,000-49,999","50,000-59,999", 
               "60,000-69,999","70,000-79,999","80,000-89,999","90,000-99,999","100,000-199,999","200,000-299,999","300,000-399,999","400,000-499,999","500,000+"]
file_rename["Home Value"] = pd.cut(file_rename["Home Value"], bins, labels=group_names,right=False)

In [6]:
Clean_file = read_file.to_csv("Clean File")